# YOUR CODE GOES HERE

version: '3'
services:
    postgres: 
        build: ./db
        ports:
            - '5432:5432'
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready']
            interval: 5s
            timeout: 3s
            retries: 5
            
    client:
        build: ./client
        volumes:
          # local folder : container folder
            - './client:/dockerapp'
        ports:
            - "2000:2000"
        depends_on: 
            - server 
    
    server:
        build: ./server
        volumes:
            - './server:/dockerserver'
        ports:
            - "2001:2001"
        environment:
            DB_CONNECTION_STRING: postgres://docker:password@postgres:5432/docker
        depends_on:
          postgres:
            condition: service_healthy